# Generated by Django 5.0.6 on 2024-07-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_id', models.CharField(max_length=255)),
                ('Blog_title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'blog_Table',
            },
        ),
    ]
